#!/bin/sh

jump_db_file=$HOME/.jump_db

jump() {
    all_directories=$(cat $jump_db_file)

    selected_directory=$(echo "$all_directories" | fzf)

    cd "$selected_directory"
}

build_jump_db() {
    all_directories=$(find / -type d 2> /dev/null)

    echo "$all_directories" | sort | uniq > $jump_db_file
}
